import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
// esta libreria 'react-hot-toast' con su Componente Toaster es para mostrar pequeñas alertas en la pagina
// COLOCAMOS EL COMPONENTE DE FORMA GLOBAL PARA QUE PUEDA MOSTRAR EN CUALQUIERA PARTE DE NUESTRO PROYECTO
import { Toaster } from "react-hot-toast";
import { auth, signOut } from "@/auth";
import Sidebar from "./(interface)/components/Sidebar";

import { Button } from "@/components/ui/button";
import { ChevronRight } from "lucide-react";
import Content from "./(interface)/components/Content";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!!session) {
    return (
      <html lang="es">
        <body className={inter.className}>
          <div className="flex flex-col md:flex-row">
            
          <Sidebar />

            <main className="flex-1 flex flex-col items-center p-4 ml-20 md:ml-20">
              <div className="flex justify-between items-center mb-6 w-full">

              <div className="flex items-center space-x-4">
                  <p className="font">
                    Hola, <strong>{session.user?.name}</strong>
                  </p>

                  <form
                    action={async () => {
                      "use server";
                      await signOut();
                    }}
                  >
                    <Button type="submit">Cerrar Sesión</Button>
                  </form>
                </div>

                <Link
                  href={"/protected"}
                  className="h-10 rounded-md border border-zinc-950 text-zinc-950 flex gap-1 items-center justify-center px-6 text-sm"
                >
                  <span>Ir a ruta protegida</span>
                  <ChevronRight className="w-4 h-4" />
                </Link>
              </div>

              <Content />

              <div className="flex-60 w-full max-w-7xl bg-white rounded-lg shadow-md p-6 overflow-y-auto">
                  {children}
                </div>
              <Toaster />
            </main>
          </div>
        </body>
      </html>
    );
  } else {
    return (
      <html lang="es">
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </html>
    );
  }
}
